version: '2.1'

services:
  postgres:
    image: postgres:latest
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 10s
        retries: 5

  django:
    image: django-pg:latest
    container_name: django_blog
    ports:
        - "8000:8000"
    depends_on:
        postgres:
          condition: service_healthy